sudo: required
servies: 
    -docker

before_install:
    - docker build -t gwaghmare/docker-react -f Dockerfile.dev .
script:
    - docker run gwaghmare/docker-react npm run test -- --coverage
deploy:
    provide: elasticbeanstalk
    region: "ap-south-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-004691489732"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"